using System;
using System.Collections.Generic;
using UnityEngine;

namespace QPathFinder
{
    public class MoveToNode : MonoBehaviour
    {
        public GameObject playerObj;
        public float playerSpeed = 20.0f;
        

        void OnGUI()
        {
            if ( PathFinder.instance == null && PathFinder.instance.graphData != null ) 
                return;
            {
                int y = 0;
                foreach ( var go in PathFinder.instance.graphData.nodes  )
                {
                    if ( GUI.Button ( new Rect ( Screen.width - 150, y*30, 150, 30), "Node:" + go.autoGeneratedID.ToString() ))
                    {
                        MoveTo( go );
                    }
                    y++;
                }
            }
        }

        void MoveTo( Node node )
        {
            {
                PathFinder.instance.FindShortestPathOfPoints( playerObj.transform.position, node.Position,  PathFinder.instance.graphData.lineType, 
                    Execution.Asynchronously,
                    SearchMode.Simple,
                    delegate ( List<Vector3> points ) 
                    { 
                        PathFollowerUtility.StopFollowing( playerObj.transform );
                        FollowThePathNormally ( points );
                    }
                 );
            }
        }

        

        void FollowThePathNormally ( List<Vector3> nodes )
        {
            PathFollowerUtility.FollowPath ( playerObj.transform, nodes, playerSpeed, false );
        }
    }
}
